# Generated by Django 4.2.5 on 2023-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('message', models.TextField()),
            ],
        ),
    ]
