# Generated by Django 4.2.5 on 2023-09-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='staff_photos/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
