# Generated by Django 4.2.7 on 2023-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0004_remove_staff_id_alter_staff_photo_alter_staff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
